### ISSUE TITLE
Completion rate not 100% after process reported as completed

### ISSUE THREAD

**Issue by ngirard** [arshadrr/subreddit-archiver#3]
Here's the output I got after the process completed:

```
subreddit-archiver archive --subreddit rust --file rust.sqlite --credentials credentials.txt 
Subreddit created on Thu Dec  2 22:27:18 2010
Saved 51630 posts more. Covered 90.6% of subreddit lifespan

Completed archiving
```

It doesn't make sense... what's going on here ?

**Comment by arshadrr** [comment]
Hi,

Thanks for reporting this. It's now been fixed.

The utility reports how far it has reached until when the subreddit was created, not the proportion of the posts in the subreddit is has saved.

So, suppose a subreddit were created in 2019, the first post posted on 2020 and the tool used on 2021. When the tool saves the one post in the subreddit, it would have completed archiving. But it would only have gotten to 50% of the lifespan of the subreddit (2020, when the first post was made). This is similar to what happened in your case.

The most recent commit I made fixes this, it should now show 100% when it gets all the posts.
