### ISSUE TITLE
update with new pushshift

### ISSUE THREAD

**Issue by aarasmith** [arshadrr/subreddit-archiver#8]
Hi, I realized my archive hadn't been updating since the pushshift API changed, so I pulled your changes and went to update my archive. I immediately started getting rate limited with 429's. I realized what was happening is that with the new changes, if you request with `sort=desc` and `since=<newest_created_utc>`, it returns the newest ID's created after the `since` parameter. Moreover, it returns them newest to oldest. So with a batch size of 100, it was returning the newest 100 posts since december and then setting the newest_created_utc to the newest post on the subreddit. However, the `since` parameter is inclusive, so it then repeatedly gets a single post with the newest ID and sends it to `get_from_pushshift()` over and over very rapidly resulting in 429's.

So I changed the `sort` parameter to 'asc' when `make_pushshift_url(after=True)`, but the data returned is then oldest to newest, so in the `update_posts()` function I needed to change the index from `newest_post_utc = get_created_utc(posts[0])` to a negative index with `newest_post_utc = get_created_utc(posts[-1])` to avoid just incrementing by 1 post at a time. Not sure if it will exit cleanly as it's still updating, but it's properly updating my archive now

Other than that, love the tool and thanks for maintaining it!

**Comment by arshadrr** [comment]
This should be fixed now. Thanks for bringing it up and for detailing what was wrong, it would've certainly taken longer to fix otherwise.
